# Generated by Django 4.1.3 on 2023-04-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpredictdatamodel',
            old_name='ADV_R',
            new_name='CO2_Emission_Rating',
        ),
        migrations.RenameField(
            model_name='userpredictdatamodel',
            old_name='ADV_S',
            new_name='Cylinders',
        ),
        migrations.RenameField(
            model_name='userpredictdatamodel',
            old_name='Attack_type',
            new_name='Engine_Size',
        ),
        migrations.RenameField(
            model_name='userpredictdatamodel',
            old_name='DATA_R',
            new_name='FC_City',
        ),
        migrations.RenameField(
            model_name='userpredictdatamodel',
            old_name='DATA_S',
            new_name='FC_Comb_km',
        ),
        migrations.RenameField(
            model_name='userpredictdatamodel',
            old_name='Data_Sent_To_BS',
            new_name='FC_Comb_mpg',
        ),
        migrations.RenameField(
            model_name='userpredictdatamodel',
            old_name='Dist_To_CH',
            new_name='FC_Hwy',
        ),
        migrations.RenameField(
            model_name='userpredictdatamodel',
            old_name='Expaned_Energy',
            new_name='Fuel_Type',
        ),
        migrations.RenameField(
            model_name='userpredictdatamodel',
            old_name='Is_CH',
            new_name='Transmission',
        ),
        migrations.RemoveField(
            model_name='userpredictdatamodel',
            name='JOIN_R',
        ),
        migrations.RemoveField(
            model_name='userpredictdatamodel',
            name='JOIN_S',
        ),
        migrations.RemoveField(
            model_name='userpredictdatamodel',
            name='Rank',
        ),
        migrations.RemoveField(
            model_name='userpredictdatamodel',
            name='SCH_R',
        ),
        migrations.RemoveField(
            model_name='userpredictdatamodel',
            name='SCH_S',
        ),
        migrations.RemoveField(
            model_name='userpredictdatamodel',
            name='Time',
        ),
        migrations.RemoveField(
            model_name='userpredictdatamodel',
            name='dist_CH_To_BS',
        ),
        migrations.RemoveField(
            model_name='userpredictdatamodel',
            name='send_code',
        ),
        migrations.RemoveField(
            model_name='userpredictdatamodel',
            name='who_CH',
        ),
    ]
